#
# Copyright (c) 2020 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# General
CONFIG_AWS_IOT_SAMPLE_APP_VERSION="v1.0.1"
CONFIG_LOG=y
CONFIG_LOG_BUFFER_SIZE=2048
CONFIG_HW_ID_LIBRARY=y
CONFIG_ASSERT=y
CONFIG_JSON_LIBRARY=y
CONFIG_REBOOT=y
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_IMG_MANAGER=y
# Heap and stacks
CONFIG_HEAP_MEM_POOL_SIZE=8096
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=12288
#CONFIG_NET_CONNECTION_MANAGER_MONITOR_STACK_SIZE=4096
CONFIG_NET_MGMT_EVENT_STACK_SIZE=8192
#CONFIG_NRF_MODEM_LIB_NET_IF_WORKQUEUE_STACK_SIZE=2048

# Network
CONFIG_NETWORKING=y
CONFIG_NET_NATIVE=y
CONFIG_NET_IPV4=y
CONFIG_NET_CONNECTION_MANAGER=y
# AT host library
CONFIG_LTE_LINK_CONTROL=y
CONFIG_MODEM_KEY_MGMT=y
#CONFIG_LTE_NETWORK_MODE_LTE_M=y
CONFIG_LTE_NETWORK_MODE_LTE_M_NBIOT=y
CONFIG_LTE_LOCK_BANDS=y                           
CONFIG_LTE_LOCK_BAND_MASK="10000000000000000000" 

CONFIG_LTE_UNLOCK_PLMN=y
# Heaps and stacks

# AWS IoT library
CONFIG_AWS_IOT=y
CONFIG_AWS_IOT_CLIENT_ID_STATIC=""
CONFIG_AWS_IOT_BROKER_HOST_NAME="abcxxeu-west-1.amazonaws.com"
CONFIG_AWS_IOT_SAMPLE_DEVICE_ID_USE_HW_ID=y
CONFIG_MQTT_HELPER_SEC_TAG=40
CONFIG_AWS_IOT_TOPIC_UPDATE_DELTA_SUBSCRIBE=n
CONFIG_AWS_IOT_TOPIC_GET_ACCEPTED_SUBSCRIBE=n
CONFIG_AWS_IOT_TOPIC_GET_REJECTED_SUBSCRIBE=n


# MQTT helper library

CONFIG_MQTT_HELPER=y
#CONFIG_MQTT_HELPER_SEC_TAG=201
CONFIG_MQTT_HELPER_LAST_WILL=y
CONFIG_MQTT_HELPER_STACK_SIZE=4096

# MQTT - Maximum MQTT keepalive timeout specified by AWS IoT Core
CONFIG_MQTT_KEEPALIVE=1200
CONFIG_MQTT_CLEAN_SESSION=y
CONFIG_MQTT_HELPER_PROVISION_CERTIFICATES=y
CONFIG_MQTT_HELPER_NATIVE_TLS=y
# Increased AWS IoT payload buffer to be able to receive large payloads when using native TLS.
CONFIG_MQTT_HELPER_PAYLOAD_BUFFER_LEN=8096

CONFIG_HW_ID_LIBRARY_SOURCE_IMEI=y
CONFIG_NET_SOCKETS_SOCKOPT_TLS=y
CONFIG_MQTT_HELPER_CERTIFICATES_FOLDER="claim-certs"

# Native network stack
CONFIG_NRF_SECURITY=y
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_ENABLE_HEAP=y
#CONFIG_MBEDTLS_HEAP_SIZE= 56320
#81920
CONFIG_MBEDTLS_RSA_C=y

# NET Sockets
CONFIG_NET_SOCKETS_TLS_MAX_CONTEXTS=1
CONFIG_AWS_IOT_FLEET_PROVISION_CHANGES=y
CONFIG_AWS_IOT_SAMPLE_PUBLICATION_INTERVAL_SECONDS=60



#NVS Configuration
CONFIG_FLASH=y

CONFIG_NVS=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_NVS_LOG_LEVEL_DBG=y
CONFIG_REBOOT=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_BOOT_BANNER=y
CONFIG_AWS_FOTA=y
CONFIG_AWS_JOBS=y

CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_NRF_MODEM_LIB_TRACE=n
CONFIG_NRF_MODEM_LIB_TRACE_BACKEND_UART=n
#CONFIG_UART_1_INTERRUPT_DRIVEN=y
#CONFIG_UART_LINE_CTRL=n
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y



CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000  
# Default for SysTick (1ms tick rate)
CONFIG_TICKLESS_KERNEL=n  
# Disable tickless mode if you need regular SysTick ticks
CONFIG_CLOCK_CONTROL=y    
# Enable clock control
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y 



CONFIG_WATCHDOG_APPLICATION=y



